export const pokelist = [
  {
    id: 1,
    name: "bulbasaur",
    types: "planta",
    icon: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Pok%C3%A9mon_Grass_Type_Icon.svg",
    evolution: null,
    url: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon//versions/generation-v/black-white/animated/1.gif",
  },
  {
    id: 2,
    name: "ivysaur",
    types: "planta",
    icon: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Pok%C3%A9mon_Grass_Type_Icon.svg",
    evolution: "bulbasaur",
    url: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon//versions/generation-v/black-white/animated/2.gif",
  },
  {
    id: 3,
    name: "venusaur",
    types: "planta",
    icon: "https://upload.wikimedia.org/wikipedia/commons/f/f6/Pok%C3%A9mon_Grass_Type_Icon.svg",
    evolution: "ivysaur",
    url: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon//versions/generation-v/black-white/animated/female/3.gif",
  },
  {
    id: 4,
    name: "charmander",
    types: "fuego",
    icon: "https://upload.wikimedia.org/wikipedia/commons/5/56/Pok%C3%A9mon_Fire_Type_Icon.svg",
    evolution: null,
    url: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon//versions/generation-v/black-white/animated/4.gif",
  },
  {
    id: 5,
    name: "charmeleon",
    types: "fuego",
    icon: "https://upload.wikimedia.org/wikipedia/commons/5/56/Pok%C3%A9mon_Fire_Type_Icon.svg",
    evolution: "charmander",
    url: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon//versions/generation-v/black-white/animated/5.gif",
  },
  {
    id: 6,
    name: "charizard",
    types: "fuego",
    icon: "https://upload.wikimedia.org/wikipedia/commons/5/56/Pok%C3%A9mon_Fire_Type_Icon.svg",
    evolution: "charmeleon",
    url: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon//versions/generation-v/black-white/animated/6.gif",
  },
  {
    id: 7,
    name: "squirtle",
    types: "agua",
    icon: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Pok%C3%A9mon_Water_Type_Icon.svg",
    evolution: null,
    url: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon//versions/generation-v/black-white/animated/7.gif",
  },
  {
    id: 8,
    name: "wartortle",
    types: "agua",
    icon: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Pok%C3%A9mon_Water_Type_Icon.svg",
    evolution: "squirtle",
    url: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon//versions/generation-v/black-white/animated/8.gif",
  },
  {
    id: 9,
    name: "blastoise",
    types: "agua",
    icon: "https://upload.wikimedia.org/wikipedia/commons/0/0b/Pok%C3%A9mon_Water_Type_Icon.svg",
    evolution: "wartortle",
    url: "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon//versions/generation-v/black-white/animated/9.gif",
  },
 
];
